INSERT INTO PERSON
(ID,NAME,LOCATION,BIRTH_DATE)
VALUES(1001,'ABC','MUMBAI',sysdate());

INSERT INTO PERSON
(ID,NAME,LOCATION,BIRTH_DATE)
VALUES(1003,'PQR','DELHI',sysdate());

INSERT INTO PERSON
(ID,NAME,LOCATION,BIRTH_DATE)
VALUES(1005,'XYZ','HYDERABAD',sysdate());


